[2022-10-27 02:20:19,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-10-27T02:20:17.398602+00:00 [queued]>
[2022-10-27 02:20:19,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2022-10-27T02:20:17.398602+00:00 [queued]>
[2022-10-27 02:20:19,637] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 02:20:19,639] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-27 02:20:19,640] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-27 02:20:19,673] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-27 02:20:17.398602+00:00
[2022-10-27 02:20:19,698] {standard_task_runner.py:52} INFO - Started process 346 to run task
[2022-10-27 02:20:19,746] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2022-10-27T02:20:17.398602+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp8a9l6_c1', '--error-file', '/tmp/tmpk1ayv0j_']
[2022-10-27 02:20:19,749] {standard_task_runner.py:80} INFO - Job 11: Subtask is_api_available
[2022-10-27 02:20:20,043] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available manual__2022-10-27T02:20:17.398602+00:00 [running]> on host 18112c9f481e
[2022-10-27 02:20:20,358] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-27T02:20:17.398602+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-27T02:20:17.398602+00:00
[2022-10-27 02:20:20,375] {http.py:97} INFO - Poking: api/
[2022-10-27 02:20:20,399] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-27 02:20:20,408] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-10-27 02:20:21,106] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-27 02:20:21,157] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221027T022017, start_date=20221027T022019, end_date=20221027T022021
[2022-10-27 02:20:21,232] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-27 02:20:21,296] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
